server:
  port: 9002

inventory:
  topic:
    name: inventory-topic
  group:
    name: cart-group-id


spring:
  application:
    name: cart
  datasource:
    url: jdbc:h2:mem:cartdb
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: localhost:9092
    #producer:
      #key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: cart-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring:
        json:
          trusted:
            packages: com.rpf.inventory.beans
